---
baseurl: "https://linuxyunwei.com/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-CN"
title: "戴先森的学习笔记"
theme: "Lovelt"
metaDataFormat: "yaml"
algolia:
  index: "linuxyunwei.com"
  key: "03c7a5c4ad6545a7aa6a3b1b997a1275"
  appID: "QK0DPR8U9U"
---

