baseURL = "https://linuxyunwei.com/"
title = "戴先森的学习笔记"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"

preserveTaxonomyNames = false
enableRobotsTXT = true
enableEmoji = true

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true
pygmentsUseClasses = true
# pygmentsUseClassic = false
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "vs"
pygmentsOptions = "linenos=table"

theme = "LoveIt"
enableGitInfo = true  # 可根据 Git 中的提交生成最近更新记录。
hasCJKLanguage = true  # 自动检测是否包含 中文\日文\韩文
paginate = 5  # 首页每页显示的文章数
rssLimit = 20  # 限制 Rss 文章输出数量

# copyright = '戴先森 &#183; <a rel="license noopener" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a><br /><a href="http://www.miitbeian.gov.cn/" target="_blank">沪ICP备13017200号-1</a> <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31011202011734"><img src="//p.ssl.qhmsg.com/t01d8eda6e551cf2615.png"/>沪公网安备 31011202011734号</p></a>'
# mainSections = ["posts"]

# Enable author pages
# [taxonomies]
#  author = "author"
#  post = "posts"
#  tag = "tags"
#  category = "categories"

[author]
  name = "戴先森"
  email = "daixijun1990@gmail.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "文章列表"
  weight = 20
  identifier = "posts"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  # LoveIt 主题版本
  version = "0.2.X"
  # AuthorName = "戴先森"
  # GitHubUser = "daixijun"
  # Subtitle = "关注Kubernetes、Istio、云原生、服务网络、Ansible等技术"
  # since = "2019"
  # toc = true
  # homeFullContent = false
  # rssFullContent = true
  # logoTitle = "Xijun Dai"
  # 网站关键字
  keywords = ["docker", "k8s", "kubernetes", "servicemesh", "istio", "ansible", "python", "golang"]
  # 网站描述
  description = "戴先森的学习笔记"
  # 网站默认主题样式 ("light", "dark", "auto")
  defaultTheme = "auto"
  # archivePaginate = 50
  # showArchiveCount = true
  # showAuthorInfo = true
  # photoswipe = true
  # moreMeta = true
  # 日期格式
  dateFormat = "2006-01-02"
  # dateformShort   = "Jan 2"
  # dateformNum     = "2006-01-02"
  # dateformNumTime = "2006-01-02 15:04"
  # dateFormatToUse = "2006-01-02 15:04:06"
  # highlightInClient = true
  # contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  gitRepo = "https://github.com/linuxyunwei/linuxyunwei.com"

  # 应用图标配置
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "LoveIt"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10磁贴颜色
    tileColor = "#da532c"

  # 搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ("lunr", "algolia")
    type = "algolia"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # 最大结果数目
    maxResultLength = 10
    # 结果内容片段长度
    snippetLength = 50
    # 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false

    [params.search.algolia]
      index = "linuxyunwei.com"
      appID = "QK0DPR8U9U"
      searchKey = "ed629decd2fd8c246289576b705eb412"

  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    # 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = ""
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # 是否为标题显示打字机动画
      typeit = false

  # [params.reward]
  #   enable = true
  #   wechat = "//static.linuxyunwei.com/wechat-qr-code.jpg"           # 微信二维码
  #   alipay = "//static.linuxyunwei.com/alipay-qr-code.jpg"           # 支付宝二维码

  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = '<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31011202011734"><img src="//p.ssl.qhmsg.com/t01d8eda6e551cf2615.png"/>沪公网安备 31011202011734号</p></a>'
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = true
    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = true
    # site creation time
    # 网站创立年份
    since = 2019
    # ICP info only in China (HTML format is supported)
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = "沪ICP备13017200号"
    # license info (HTML format is supported)
    # 许可协议信息 (支持 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # 主页配置
  [params.home]
    # RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = "daixijun1990@gmail.com"
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.png"
      # 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # 主页显示的网站副标题
      subtitle = ""
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6
      # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false

  # 作者的社交信息设置
  [params.social]
    GitHub = "daixijun"
    Linkedin = ""
    Twitter = "daixijun1990"
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = "daixijun"
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = "daixijun"
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Email = "daixijun1990@gmail.com"
    RSS = true

  # LoveIt 更改 | 0.2.0 文章页面配置
  [params.page]
    # LoveIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # LoveIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # LoveIt 新增 | 0.2.0 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = true
    # LoveIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # LoveIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # LoveIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # LoveIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    # LoveIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # 是否使目录自动折叠展开
      auto = true
    # LoveIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 50
    # LoveIt 更改 | 0.2.0 KaTeX 数学公式
    [params.page.math]
      enable = true
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # LoveIt 新增 | 0.2.0 Mapbox GL JS 配置
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    # LoveIt 更改 | 0.2.0 文章页面的分享信息设置
    [params.page.share]
      enable = false
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false
    # LoveIt 更改 | 0.2.0 评论系统设置
    [params.page.comment]
      enable = true
      # Disqus 评论系统设置
      [params.page.comment.disqus]
        # LoveIt 新增 | 0.1.1
        enable = false
        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = ""
      # Gitalk 评论系统设置
      [params.page.comment.gitalk]
        # LoveIt 新增 | 0.1.1
        enable = true
        owner = "linuxyunwei"
        repo = "linuxyunwei.com"
        clientId = "e0ebb50b7471a999a10f"
        clientSecret = "1c47fb3b5af8c3f7840e0e8a8cd5b69ee10b682f"
      # Valine 评论系统设置
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        # LoveIt 新增 | 0.2.6 emoji 数据文件名称, 默认是 "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # 位于 "themes/LoveIt/assets/data/emoji/" 目录
        # 可以在你的项目下相同路径存放你自己的数据文件:
        # "assets/data/emoji/"
        emoji = ""
      # Facebook 评论系统设置
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = "zh_CN"
      # LoveIt 新增 | 0.2.0 Telegram Comments 评论系统设置
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      # LoveIt 新增 | 0.2.0 Commento 评论系统设置
      [params.page.comment.commento]
        enable = false
      # LoveIt 新增 | 0.2.5 Utterances 评论系统设置
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
    # LoveIt 新增 | 0.2.7 第三方库配置
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # 位于 "assets/"
        # 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # 位于 "assets/"
        # 或者
        # someJavascript = "https://cdn.example.com/some.js"
    # LoveIt 新增 | 0.2.0 SEO config
    [params.page.seo]
      # 出版者信息
      [params.page.seo.publisher]
        name = "xxxx"
        [params.page.seo.publisher.logo]
          url = "logo.png"
          width = 127
          height = 40
      # Logo 信息
      [params.page.seo.logo]
        url = "logo.png"
        width = 127
        height = 40
      # 图片信息
      [params.page.seo.image]
        url = "cover.png"
        width = 800
        height = 600

  # TypeIt 配置
  [params.typeit]
    # 每一步的打字速度 (单位是毫秒)
    speed = 100
    # 光标的闪烁速度 (单位是毫秒)
    cursorSpeed = 1000
    # 光标的字符 (支持 HTML 格式)
    cursorChar = "|"
    # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
    duration = -1

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # 网站分析配置
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""

  # Cookie 许可配置
  [params.cookieconsent]
    enable = true
    # 用于 Cookie 许可横幅的文本字符串
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  # 第三方库文件的 CDN 设置
  [params.cdn]
    # CDN 数据文件名称, 默认不启用
    # ("jsdelivr.yml")
    # 位于 "themes/LoveIt/assets/data/cdn/" 目录
    # 可以在你的项目下相同路径存放你自己的数据文件:
    # "assets/data/cdn/"
    data = ""

  # 兼容性设置
  [params.compatibility]
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
[permalinks]
  posts = "/:title/"

[outputs]
  home = ["HTML", "RSS", "JSON"]